// <auto-generated />
using System;
using MSP.Infrastructure.Persistence.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MSP.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117090543_AddReviewerToProjectTask")]
    partial class AddReviewerToProjectTask
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MSP.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Limitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUnlimited")
                        .HasColumnType("boolean");

                    b.Property<string>("LimitUnit")
                        .HasColumnType("text");

                    b.Property<int?>("LimitValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Limitations");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MilestoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecordUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transcription")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MSP.Domain.Entities.OrganizationInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessOwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("BusinessOwnerId", "Status");

                    b.HasIndex("MemberId", "Status");

                    b.ToTable("OrganizationInvitations");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BillingCycle")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MSP.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("MSP.Domain.Entities.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOverdue")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TodoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TodoId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectTasks");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("TransactionID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("MSP.Domain.Entities.TaskHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldName")
                        .HasColumnType("text");

                    b.Property<Guid?>("FromUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("FromUserId");

                    b.HasIndex("TaskId");

                    b.HasIndex("ToUserId");

                    b.ToTable("TaskHistories");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("UserId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("MSP.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("BusinessLicense")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ManagedById")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedById");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-4789-1234-56789abcdef2"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "79424eea-65f2-44ad-a217-98008705ba8e",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Nguyen Van An",
                            IsActive = true,
                            IsApproved = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEDTqa7Ovccl70TjP95telRhdyJFLfPflIJVLgNYnBxBfjxhj2fWIfkqkHY5VOYwPCQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1dfd4c7d-0d79-44af-bf3f-ead4e7b11343",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("c2d4e3f4-a5b6-4789-1234-56789abcdef2"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bedc9324-d05a-4160-85d8-a89440b2fb77",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member1@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Le Thi Thuy",
                            IsActive = true,
                            IsApproved = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER1@GMAIL.COM",
                            NormalizedUserName = "MEMBER",
                            PasswordHash = "AQAAAAIAAYagAAAAECqa+NcXq37nwxbzk5Vgq86fq+rNUtZz0HoCQdhcJLTzu2R3QpDRrbLNw6ZxH3NjyA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7a4dfea4-6a65-42b0-8f83-2cffd5073f47",
                            TwoFactorEnabled = false,
                            UserName = "Member"
                        },
                        new
                        {
                            Id = new Guid("d2a5b3c4-d7e8-4789-1234-56789abcdef3"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a762ae92-973b-4994-990c-b9b9d3789eb1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member2@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Pham Minh Hieu",
                            IsActive = true,
                            IsApproved = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER2@GMAIL.COM",
                            NormalizedUserName = "MEMBER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEJlid4OZ7JBc3tJVNzznoxseqsxnGO+NTgy2R2Q5Nt8U9spu/mmC3NcGlng9wn3jWQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "46fab13c-f5e1-4a86-9464-35927e1d0916",
                            TwoFactorEnabled = false,
                            UserName = "Member2"
                        },
                        new
                        {
                            Id = new Guid("e3b6c7d8-a9f0-4789-1234-56789abcdef4"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "34000a2b-0173-4090-bab3-01d0a3f3813c",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member3@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Nguyen Bao Chau",
                            IsActive = true,
                            IsApproved = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER3@GMAIL.COM",
                            NormalizedUserName = "MEMBER3",
                            PasswordHash = "AQAAAAIAAYagAAAAEJw7vj045Ut9jhUXSWfPJNfEljKQhoB7HNjuMGLQ2xLvLCwtEsRqYsaYU1zQuW+mwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "be5dbd1e-5c13-4931-9430-4232af9534c4",
                            TwoFactorEnabled = false,
                            UserName = "Member3"
                        },
                        new
                        {
                            Id = new Guid("f4c7d8e9-b1a2-4789-1234-56789abcdef5"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "782f84c8-17fd-4d52-bd57-1b8b1faf522b",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member4@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Do Thi Lan Anh",
                            IsActive = true,
                            IsApproved = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER4@GMAIL.COM",
                            NormalizedUserName = "MEMBER4",
                            PasswordHash = "AQAAAAIAAYagAAAAEJzPT86iTg/3WqpMkP3Q6qR5ntHt6HyzYP95IniXFEnGd5R3SSeZr7zzpDYuuXy5MQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cf6d215f-f4eb-4413-aa1f-c3745b1b74ef",
                            TwoFactorEnabled = false,
                            UserName = "Member4"
                        },
                        new
                        {
                            Id = new Guid("c3d4e3f4-a5b6-4789-1234-56789abcdef2"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8ece264d-10c1-471d-a881-0f99c7364f4f",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pm@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Tran Van Binh",
                            IsActive = true,
                            IsApproved = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PM@GMAIL.COM",
                            NormalizedUserName = "PROJECTMANAGER",
                            PasswordHash = "AQAAAAIAAYagAAAAEHFJIAZ1LS0ODkjT97JNVDOrGXWjTYPKdoeWi5vPUD6fQN42vdzvurt4WZl8RQorsg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cf4500ba-0b20-429f-aa57-bde0557aba9f",
                            TwoFactorEnabled = false,
                            UserName = "ProjectManager"
                        },
                        new
                        {
                            Id = new Guid("c4d4e3f4-a5b6-4789-1234-56789abcdef2"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "84b622de-7225-4830-ae45-2699ffd4c0c1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bo1@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Ngo Van Thanh",
                            IsActive = true,
                            IsApproved = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BO1@GMAIL.COM",
                            NormalizedUserName = "BUSINESSOWNER",
                            Organization = "FPT Software",
                            PasswordHash = "AQAAAAIAAYagAAAAEEXU8bQIOfuQey82dCRuGS06PjAUcIgnxWE5u42NjTvfEMCi3eEIOYRgrFTWGGY0ew==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "31675d89-03b8-491e-b5c2-7ec0bc637e31",
                            TwoFactorEnabled = false,
                            UserName = "BusinessOwner"
                        },
                        new
                        {
                            Id = new Guid("a5b6c7d8-e9f0-4789-1234-56789abcdef6"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "17ea0fd7-25fc-46d7-8651-4205d192f9a4",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bo2@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Hoang Thi Hong",
                            IsActive = true,
                            IsApproved = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BO2@GMAIL.COM",
                            NormalizedUserName = "BUSINESSOWNER2",
                            Organization = "VNPT Technology",
                            PasswordHash = "AQAAAAIAAYagAAAAELGZgy+LFDYDAkYzke365z8xI7FeAmJtdJdYgrcT9Yk7d4ZrCADpZZ+Y0YZxnFc59A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "173a3834-4cf1-4f18-bab9-c507908d350c",
                            TwoFactorEnabled = false,
                            UserName = "BusinessOwner2"
                        },
                        new
                        {
                            Id = new Guid("b6c7d8e9-f0a1-4789-1234-56789abcdef7"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "95aa81e4-144d-4a59-a2fb-cd55eabcccba",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bo3@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Le Van Phuc",
                            IsActive = true,
                            IsApproved = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BO3@GMAIL.COM",
                            NormalizedUserName = "BUSINESSOWNER3",
                            Organization = "CMC Corporation",
                            PasswordHash = "AQAAAAIAAYagAAAAEKuaUWgfl5E2e8lmPvDFuwLNk2zK/oh0bl8zcIUV02MOrO5R8b54AA7eMyG6DJOYUA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d348dbd6-298e-4f3d-aaeb-e9e7a60fd515",
                            TwoFactorEnabled = false,
                            UserName = "BusinessOwner3"
                        });
                });

            modelBuilder.Entity("MeetingUser", b =>
                {
                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("MeetingId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("MeetingUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-1234-56789abcdef0"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-4789-1234-56789abcdef1"),
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-4789-1234-56789abcdef2"),
                            Name = "ProjectManager",
                            NormalizedName = "PROJECTMANAGER"
                        },
                        new
                        {
                            Id = new Guid("d1e2f3a4-b5c6-4789-1234-56789abcdef3"),
                            Name = "BusinessOwner",
                            NormalizedName = "BUSINESSOWNER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c1d2e3f4-a5b6-4789-1234-56789abcdef2"),
                            RoleId = new Guid("a1b2c3d4-e5f6-4789-1234-56789abcdef0")
                        },
                        new
                        {
                            UserId = new Guid("c2d4e3f4-a5b6-4789-1234-56789abcdef2"),
                            RoleId = new Guid("b1c2d3e4-f5a6-4789-1234-56789abcdef1")
                        },
                        new
                        {
                            UserId = new Guid("d2a5b3c4-d7e8-4789-1234-56789abcdef3"),
                            RoleId = new Guid("b1c2d3e4-f5a6-4789-1234-56789abcdef1")
                        },
                        new
                        {
                            UserId = new Guid("e3b6c7d8-a9f0-4789-1234-56789abcdef4"),
                            RoleId = new Guid("b1c2d3e4-f5a6-4789-1234-56789abcdef1")
                        },
                        new
                        {
                            UserId = new Guid("f4c7d8e9-b1a2-4789-1234-56789abcdef5"),
                            RoleId = new Guid("b1c2d3e4-f5a6-4789-1234-56789abcdef1")
                        },
                        new
                        {
                            UserId = new Guid("c3d4e3f4-a5b6-4789-1234-56789abcdef2"),
                            RoleId = new Guid("c1d2e3f4-a5b6-4789-1234-56789abcdef2")
                        },
                        new
                        {
                            UserId = new Guid("c4d4e3f4-a5b6-4789-1234-56789abcdef2"),
                            RoleId = new Guid("d1e2f3a4-b5c6-4789-1234-56789abcdef3")
                        },
                        new
                        {
                            UserId = new Guid("a5b6c7d8-e9f0-4789-1234-56789abcdef6"),
                            RoleId = new Guid("d1e2f3a4-b5c6-4789-1234-56789abcdef3")
                        },
                        new
                        {
                            UserId = new Guid("b6c7d8e9-f0a1-4789-1234-56789abcdef7"),
                            RoleId = new Guid("d1e2f3a4-b5c6-4789-1234-56789abcdef3")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MilestoneTask", b =>
                {
                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("MilestoneId", "ProjectTaskId");

                    b.HasIndex("ProjectTaskId");

                    b.ToTable("MilestoneTasks", (string)null);
                });

            modelBuilder.Entity("PackageLimitation", b =>
                {
                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LimitationId")
                        .HasColumnType("uuid");

                    b.HasKey("PackageId", "LimitationId");

                    b.HasIndex("LimitationId");

                    b.ToTable("PackageLimitations", (string)null);
                });

            modelBuilder.Entity("ProjectTaskTodo", b =>
                {
                    b.Property<Guid>("ReferencedTasksId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferencingTodosId")
                        .HasColumnType("uuid");

                    b.HasKey("ReferencedTasksId", "ReferencingTodosId");

                    b.HasIndex("ReferencingTodosId");

                    b.ToTable("ProjectTaskTodo");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Comment", b =>
                {
                    b.HasOne("MSP.Domain.Entities.ProjectTask", "ProjectTask")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectTask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Document", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.Project", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Meeting", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.Milestone", "Milestone")
                        .WithMany()
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MSP.Domain.Entities.Project", "Project")
                        .WithMany("Meetings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Milestone");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Milestone", b =>
                {
                    b.HasOne("MSP.Domain.Entities.Project", "Project")
                        .WithMany("Milestones")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MSP.Domain.Entities.OrganizationInvitation", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "BusinessOwner")
                        .WithMany("OrganizationInvitationsAsOwner")
                        .HasForeignKey("BusinessOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", "Member")
                        .WithMany("OrganizationInvitationsAsMember")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessOwner");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Package", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Project", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MSP.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MSP.Domain.Entities.ProjectTask", b =>
                {
                    b.HasOne("MSP.Domain.Entities.Project", "Project")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MSP.Domain.Entities.Todo", "Todo")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MSP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Project");

                    b.Navigation("Reviewer");

                    b.Navigation("Todo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("MSP.Domain.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MSP.Domain.Entities.TaskHistory", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MSP.Domain.Entities.ProjectTask", "Task")
                        .WithMany("TaskHistories")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChangedBy");

                    b.Navigation("FromUser");

                    b.Navigation("Task");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Todo", b =>
                {
                    b.HasOne("MSP.Domain.Entities.Meeting", "Meeting")
                        .WithMany("Todos")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Meeting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MSP.Domain.Entities.User", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "ManagedBy")
                        .WithMany("ManagedUsers")
                        .HasForeignKey("ManagedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ManagedBy");
                });

            modelBuilder.Entity("MeetingUser", b =>
                {
                    b.HasOne("MSP.Domain.Entities.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MilestoneTask", b =>
                {
                    b.HasOne("MSP.Domain.Entities.Milestone", null)
                        .WithMany()
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.ProjectTask", null)
                        .WithMany()
                        .HasForeignKey("ProjectTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PackageLimitation", b =>
                {
                    b.HasOne("MSP.Domain.Entities.Limitation", null)
                        .WithMany()
                        .HasForeignKey("LimitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectTaskTodo", b =>
                {
                    b.HasOne("MSP.Domain.Entities.ProjectTask", null)
                        .WithMany()
                        .HasForeignKey("ReferencedTasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.Todo", null)
                        .WithMany()
                        .HasForeignKey("ReferencingTodosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MSP.Domain.Entities.Meeting", b =>
                {
                    b.Navigation("Todos");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Project", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Meetings");

                    b.Navigation("Milestones");

                    b.Navigation("ProjectMembers");

                    b.Navigation("ProjectTasks");
                });

            modelBuilder.Entity("MSP.Domain.Entities.ProjectTask", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("TaskHistories");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Todo", b =>
                {
                    b.Navigation("ProjectTasks");
                });

            modelBuilder.Entity("MSP.Domain.Entities.User", b =>
                {
                    b.Navigation("ManagedUsers");

                    b.Navigation("Notifications");

                    b.Navigation("OrganizationInvitationsAsMember");

                    b.Navigation("OrganizationInvitationsAsOwner");
                });
#pragma warning restore 612, 618
        }
    }
}
